# Generated by Django 5.2.8 on 2025-11-17 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("equipment", "Equipment"),
                            ("service", "Service"),
                            ("parking", "Parking"),
                            ("locker", "Locker"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[
                            ("hour", "By hour"),
                            ("day", "By day"),
                            ("month", "By month"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("finished", "Finished"),
                            ("conflicted", "Conflicted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "parent_relation_type",
                    models.CharField(
                        blank=True,
                        help_text="Тип связи с родительской бронью",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_bookings",
                        to="bookings.booking",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("extend", "Extend"),
                            ("cancel", "Cancel"),
                            ("move", "Move"),
                            ("update", "Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_start", models.DateTimeField(blank=True, null=True)),
                ("old_end", models.DateTimeField(blank=True, null=True)),
                ("new_start", models.DateTimeField(blank=True, null=True)),
                ("new_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
    ]
