# Generated by Django 5.2.8 on 2025-11-18 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="send_status",
        ),
        migrations.AddField(
            model_name="notification",
            name="service_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="services.serviceorder",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка при отправке"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="Уведомление", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("telegram", "Telegram"),
                    ("internal", "Внутреннее уведомление"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Создано бронирование"),
                    ("booking_extended", "Продлено бронирование"),
                    ("booking_cancelled", "Отменено бронирование"),
                    ("issue_created", "Создано обращение о проблеме"),
                    ("issue_confirmed", "Обращение подтверждено администратором"),
                    ("service_order_created", "Создан заказ услуги"),
                ],
                max_length=50,
            ),
        ),
    ]
