# Generated by Django 5.2.8 on 2025-11-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_remove_notification_send_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("telegram", "Telegram"),
                    ("internal", "Внутреннее уведомление"),
                    ("system", "Системное уведомление"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Создано бронирование"),
                    ("booking_extended", "Продлено бронирование"),
                    ("booking_cancelled", "Отменено бронирование"),
                    ("booking_reassigned", "Бронирование перенесено на другой ресурс"),
                    ("booking_conflicted", "Бронирование в конфликте"),
                    ("issue_created", "Создано обращение о проблеме"),
                    ("issue_confirmed", "Обращение подтверждено администратором"),
                    ("issue_rejected", "Обращение отклонено администратором"),
                    ("service_order_created", "Создан заказ услуги"),
                ],
                max_length=50,
            ),
        ),
    ]
