# Generated by Django 5.2.8 on 2025-11-18 17:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("issues", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="resourceoutage",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="resourceoutage",
            name="outage_end",
        ),
        migrations.RemoveField(
            model_name="resourceoutage",
            name="outage_start",
        ),
        migrations.AddField(
            model_name="issue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="resourceoutage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 18, 17, 32, 0, 155513, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourceoutage",
            name="end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 18, 17, 32, 14, 243478, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourceoutage",
            name="start_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 18, 17, 32, 17, 84209, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issue",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                help_text="Бронь, в рамках которой возникла проблема",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(
                choices=[("workspace", "Рабочее место"), ("equipment", "Оборудование")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Конкретный ресурс (рабочее место или оборудование)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="resources.resource",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("confirmed", "Подтверждена"),
                    ("rejected", "Отклонена"),
                    ("resolved", "Решена"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resourceoutage",
            name="reason",
            field=models.CharField(
                choices=[
                    ("issue", "Неисправность по обращению пользователя"),
                    ("maintenance", "Плановое обслуживание"),
                ],
                default="issue",
                max_length=20,
            ),
        ),
    ]
