# Generated by Django 5.2.8 on 2025-11-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0002_remove_issue_processed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceoutage",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                help_text="Заявка, по которой создан этот период недоступности",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outages",
                to="issues.issue",
            ),
        ),
    ]
