# Generated by Django 5.2.8 on 2025-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0003_resourceoutage_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceoutage",
            name="capacity_reduction",
            field=models.PositiveIntegerField(
                default=1,
                help_text="На сколько единиц уменьшается capacity ресурса на этот период",
            ),
        ),
    ]
